package autocode

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/Doraemon/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	// Code generated by github.com/flipped-aurora/Doraemon/server End; DO NOT EDIT.
}
