package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/Doraemon/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	// Code generated by github.com/flipped-aurora/Doraemon/server End; DO NOT EDIT.
}
