package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/Doraemon/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	// Code generated by github.com/flipped-aurora/Doraemon/server End; DO NOT EDIT.
}
