package tool

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/Doraemon/server Begin; DO NOT EDIT.
	ToolSourceApi
	// Code generated by github.com/flipped-aurora/Doraemon/server End; DO NOT EDIT.
}
